# Example: MCPExternalAuthConfig with Header Injection
# This example shows how to configure custom HTTP header injection authentication
# for backend MCP servers that require API keys or custom authentication headers.

---
# Create a secret containing the API key or auth token
apiVersion: v1
kind: Secret
metadata:
  name: backend-api-key
  namespace: default
type: Opaque
stringData:
  api-key: "your-secret-api-key-here"

---
# Create an MCPExternalAuthConfig for header injection
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPExternalAuthConfig
metadata:
  name: api-key-header-auth
  namespace: default
spec:
  type: headerInjection
  headerInjection:
    # The name of the HTTP header to inject
    headerName: "X-API-Key"
    # Reference to the secret containing the header value
    valueSecretRef:
      name: backend-api-key
      key: api-key
    # Alternative: Use a direct value (not recommended for sensitive data)
    # value: "my-api-key"

---
# Create an MCPServer that uses header injection auth
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: api-backend
  namespace: default
spec:
  image: ghcr.io/example/mcp-api-server:latest
  transport: streamable-http
  proxyPort: 8080
  mcpPort: 8080
  groupRef: my-group
  # Reference the external auth config
  externalAuthConfigRef:
    name: api-key-header-auth

---
# Create a VirtualMCPServer that discovers the auth from the backend
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: vmcp-with-discovered-headers
  namespace: default
spec:
  groupRef:
    name: my-group
  incomingAuth:
    type: anonymous
  # Use discovered mode - vMCP will discover header injection auth from backends
  outgoingAuth:
    source: discovered
  aggregation:
    conflictResolution: prefix
  serviceType: NodePort
