// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/toolhive/pkg/auth/upstreamtoken (interfaces: TokenReader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_token_reader.go -package=mocks github.com/stacklok/toolhive/pkg/auth/upstreamtoken TokenReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	upstreamtoken "github.com/stacklok/toolhive/pkg/auth/upstreamtoken"
	storage "github.com/stacklok/toolhive/pkg/authserver/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenReader is a mock of TokenReader interface.
type MockTokenReader struct {
	ctrl     *gomock.Controller
	recorder *MockTokenReaderMockRecorder
	isgomock struct{}
}

// MockTokenReaderMockRecorder is the mock recorder for MockTokenReader.
type MockTokenReaderMockRecorder struct {
	mock *MockTokenReader
}

// NewMockTokenReader creates a new mock instance.
func NewMockTokenReader(ctrl *gomock.Controller) *MockTokenReader {
	mock := &MockTokenReader{ctrl: ctrl}
	mock.recorder = &MockTokenReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenReader) EXPECT() *MockTokenReaderMockRecorder {
	return m.recorder
}

// GetAllUpstreamCredentials mocks base method.
func (m *MockTokenReader) GetAllUpstreamCredentials(ctx context.Context, sessionID string, expected *storage.ExpectedBinding) (map[string]upstreamtoken.UpstreamCredential, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUpstreamCredentials", ctx, sessionID, expected)
	ret0, _ := ret[0].(map[string]upstreamtoken.UpstreamCredential)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllUpstreamCredentials indicates an expected call of GetAllUpstreamCredentials.
func (mr *MockTokenReaderMockRecorder) GetAllUpstreamCredentials(ctx, sessionID, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUpstreamCredentials", reflect.TypeOf((*MockTokenReader)(nil).GetAllUpstreamCredentials), ctx, sessionID, expected)
}
