// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/toolhive/pkg/auth/upstreamtoken (interfaces: TokenReader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_token_reader.go -package=mocks github.com/stacklok/toolhive/pkg/auth/upstreamtoken TokenReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenReader is a mock of TokenReader interface.
type MockTokenReader struct {
	ctrl     *gomock.Controller
	recorder *MockTokenReaderMockRecorder
	isgomock struct{}
}

// MockTokenReaderMockRecorder is the mock recorder for MockTokenReader.
type MockTokenReaderMockRecorder struct {
	mock *MockTokenReader
}

// NewMockTokenReader creates a new mock instance.
func NewMockTokenReader(ctrl *gomock.Controller) *MockTokenReader {
	mock := &MockTokenReader{ctrl: ctrl}
	mock.recorder = &MockTokenReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenReader) EXPECT() *MockTokenReaderMockRecorder {
	return m.recorder
}

// GetAllValidTokens mocks base method.
func (m *MockTokenReader) GetAllValidTokens(ctx context.Context, sessionID string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllValidTokens", ctx, sessionID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllValidTokens indicates an expected call of GetAllValidTokens.
func (mr *MockTokenReaderMockRecorder) GetAllValidTokens(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllValidTokens", reflect.TypeOf((*MockTokenReader)(nil).GetAllValidTokens), ctx, sessionID)
}
