// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_storage_driver.go -package=mocks -source=driver.go StorageDriver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/stacklok/toolhive/pkg/core"
	runner "github.com/stacklok/toolhive/pkg/runner"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageDriver is a mock of StorageDriver interface.
type MockStorageDriver struct {
	ctrl     *gomock.Controller
	recorder *MockStorageDriverMockRecorder
	isgomock struct{}
}

// MockStorageDriverMockRecorder is the mock recorder for MockStorageDriver.
type MockStorageDriverMockRecorder struct {
	mock *MockStorageDriver
}

// NewMockStorageDriver creates a new mock instance.
func NewMockStorageDriver(ctrl *gomock.Controller) *MockStorageDriver {
	mock := &MockStorageDriver{ctrl: ctrl}
	mock.recorder = &MockStorageDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageDriver) EXPECT() *MockStorageDriverMockRecorder {
	return m.recorder
}

// DeleteWorkloadState mocks base method.
func (m *MockStorageDriver) DeleteWorkloadState(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkloadState", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkloadState indicates an expected call of DeleteWorkloadState.
func (mr *MockStorageDriverMockRecorder) DeleteWorkloadState(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkloadState", reflect.TypeOf((*MockStorageDriver)(nil).DeleteWorkloadState), ctx, name)
}

// GetWorkload mocks base method.
func (m *MockStorageDriver) GetWorkload(ctx context.Context, name string) (core.Workload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkload", ctx, name)
	ret0, _ := ret[0].(core.Workload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkload indicates an expected call of GetWorkload.
func (mr *MockStorageDriverMockRecorder) GetWorkload(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkload", reflect.TypeOf((*MockStorageDriver)(nil).GetWorkload), ctx, name)
}

// ListWorkloads mocks base method.
func (m *MockStorageDriver) ListWorkloads(ctx context.Context, listAll bool, labelFilters ...string) ([]core.Workload, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, listAll}
	for _, a := range labelFilters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListWorkloads", varargs...)
	ret0, _ := ret[0].([]core.Workload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkloads indicates an expected call of ListWorkloads.
func (mr *MockStorageDriverMockRecorder) ListWorkloads(ctx, listAll any, labelFilters ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, listAll}, labelFilters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkloads", reflect.TypeOf((*MockStorageDriver)(nil).ListWorkloads), varargs...)
}

// ListWorkloadsInGroup mocks base method.
func (m *MockStorageDriver) ListWorkloadsInGroup(ctx context.Context, groupName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkloadsInGroup", ctx, groupName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkloadsInGroup indicates an expected call of ListWorkloadsInGroup.
func (mr *MockStorageDriverMockRecorder) ListWorkloadsInGroup(ctx, groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkloadsInGroup", reflect.TypeOf((*MockStorageDriver)(nil).ListWorkloadsInGroup), ctx, groupName)
}

// LoadWorkloadState mocks base method.
func (m *MockStorageDriver) LoadWorkloadState(ctx context.Context, name string) (*runner.RunConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadWorkloadState", ctx, name)
	ret0, _ := ret[0].(*runner.RunConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadWorkloadState indicates an expected call of LoadWorkloadState.
func (mr *MockStorageDriverMockRecorder) LoadWorkloadState(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadWorkloadState", reflect.TypeOf((*MockStorageDriver)(nil).LoadWorkloadState), ctx, name)
}

// MoveToGroup mocks base method.
func (m *MockStorageDriver) MoveToGroup(ctx context.Context, names []string, from, to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToGroup", ctx, names, from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToGroup indicates an expected call of MoveToGroup.
func (mr *MockStorageDriverMockRecorder) MoveToGroup(ctx, names, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToGroup", reflect.TypeOf((*MockStorageDriver)(nil).MoveToGroup), ctx, names, from, to)
}

// SaveWorkloadState mocks base method.
func (m *MockStorageDriver) SaveWorkloadState(ctx context.Context, config *runner.RunConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWorkloadState", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWorkloadState indicates an expected call of SaveWorkloadState.
func (mr *MockStorageDriverMockRecorder) SaveWorkloadState(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWorkloadState", reflect.TypeOf((*MockStorageDriver)(nil).SaveWorkloadState), ctx, config)
}
