coverage:
  ignore:
    - "cmd/help/"
    - "cmd/thv/"
    - "cmd/thv-proxyrunner/"
    - "cmd/regup/"
    - "containers/egress-proxy"
    - "docs/"
    - "examples/"
    - "hack"
    - "test/e2e"
    - "deploy"
    - "**/mocks/**/*"
  status:
    patch: false
