// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/toolhive/pkg/memory (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination mocks/mock_store.go -package mocks github.com/stacklok/toolhive/pkg/memory Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	memory "github.com/stacklok/toolhive/pkg/memory"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockStore) Archive(ctx context.Context, id string, reason memory.ArchiveReason, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, id, reason, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockStoreMockRecorder) Archive(ctx, id, reason, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockStore)(nil).Archive), ctx, id, reason, ref)
}

// Create mocks base method.
func (m *MockStore) Create(ctx context.Context, entry memory.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), ctx, entry)
}

// Delete mocks base method.
func (m *MockStore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), ctx, id)
}

// Flag mocks base method.
func (m *MockStore) Flag(ctx context.Context, id, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flag", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flag indicates an expected call of Flag.
func (mr *MockStoreMockRecorder) Flag(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flag", reflect.TypeOf((*MockStore)(nil).Flag), ctx, id, reason)
}

// Get mocks base method.
func (m *MockStore) Get(ctx context.Context, id string) (memory.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(memory.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), ctx, id)
}

// IncrementAccess mocks base method.
func (m *MockStore) IncrementAccess(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAccess", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAccess indicates an expected call of IncrementAccess.
func (mr *MockStoreMockRecorder) IncrementAccess(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAccess", reflect.TypeOf((*MockStore)(nil).IncrementAccess), ctx, id)
}

// List mocks base method.
func (m *MockStore) List(ctx context.Context, filter memory.ListFilter) ([]memory.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]memory.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), ctx, filter)
}

// ListActive mocks base method.
func (m *MockStore) ListActive(ctx context.Context) ([]memory.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]memory.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockStoreMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockStore)(nil).ListActive), ctx)
}

// ListExpired mocks base method.
func (m *MockStore) ListExpired(ctx context.Context) ([]memory.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpired", ctx)
	ret0, _ := ret[0].([]memory.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpired indicates an expected call of ListExpired.
func (mr *MockStoreMockRecorder) ListExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpired", reflect.TypeOf((*MockStore)(nil).ListExpired), ctx)
}

// Unflag mocks base method.
func (m *MockStore) Unflag(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unflag", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unflag indicates an expected call of Unflag.
func (mr *MockStoreMockRecorder) Unflag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unflag", reflect.TypeOf((*MockStore)(nil).Unflag), ctx, id)
}

// Update mocks base method.
func (m *MockStore) Update(ctx context.Context, id, content string, author memory.AuthorType, correctionNote string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, content, author, correctionNote)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoreMockRecorder) Update(ctx, id, content, author, correctionNote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStore)(nil).Update), ctx, id, content, author, correctionNote)
}

// UpdateScores mocks base method.
func (m *MockStore) UpdateScores(ctx context.Context, id string, trustScore, stalenessScore float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScores", ctx, id, trustScore, stalenessScore)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScores indicates an expected call of UpdateScores.
func (mr *MockStoreMockRecorder) UpdateScores(ctx, id, trustScore, stalenessScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScores", reflect.TypeOf((*MockStore)(nil).UpdateScores), ctx, id, trustScore, stalenessScore)
}
