// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/toolhive/pkg/vmcp/composer (interfaces: SDKElicitationRequester)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_sdk_elicitation_requester.go -package=mocks github.com/stacklok/toolhive/pkg/vmcp/composer SDKElicitationRequester
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mcp "github.com/mark3labs/mcp-go/mcp"
	gomock "go.uber.org/mock/gomock"
)

// MockSDKElicitationRequester is a mock of SDKElicitationRequester interface.
type MockSDKElicitationRequester struct {
	ctrl     *gomock.Controller
	recorder *MockSDKElicitationRequesterMockRecorder
	isgomock struct{}
}

// MockSDKElicitationRequesterMockRecorder is the mock recorder for MockSDKElicitationRequester.
type MockSDKElicitationRequesterMockRecorder struct {
	mock *MockSDKElicitationRequester
}

// NewMockSDKElicitationRequester creates a new mock instance.
func NewMockSDKElicitationRequester(ctrl *gomock.Controller) *MockSDKElicitationRequester {
	mock := &MockSDKElicitationRequester{ctrl: ctrl}
	mock.recorder = &MockSDKElicitationRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSDKElicitationRequester) EXPECT() *MockSDKElicitationRequesterMockRecorder {
	return m.recorder
}

// RequestElicitation mocks base method.
func (m *MockSDKElicitationRequester) RequestElicitation(ctx context.Context, request mcp.ElicitationRequest) (*mcp.ElicitationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestElicitation", ctx, request)
	ret0, _ := ret[0].(*mcp.ElicitationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestElicitation indicates an expected call of RequestElicitation.
func (mr *MockSDKElicitationRequesterMockRecorder) RequestElicitation(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestElicitation", reflect.TypeOf((*MockSDKElicitationRequester)(nil).RequestElicitation), ctx, request)
}
