// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_storage.go -package=mocks -source=types.go Storage,IDPTokenStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	fosite "github.com/ory/fosite"
	storage "github.com/stacklok/toolhive/pkg/authserver/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// ClientAssertionJWTValid mocks base method.
func (m *MockStorage) ClientAssertionJWTValid(ctx context.Context, jti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientAssertionJWTValid", ctx, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClientAssertionJWTValid indicates an expected call of ClientAssertionJWTValid.
func (mr *MockStorageMockRecorder) ClientAssertionJWTValid(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientAssertionJWTValid", reflect.TypeOf((*MockStorage)(nil).ClientAssertionJWTValid), ctx, jti)
}

// Close mocks base method.
func (m *MockStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// CreateAccessTokenSession mocks base method.
func (m *MockStorage) CreateAccessTokenSession(ctx context.Context, signature string, request fosite.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessTokenSession", ctx, signature, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccessTokenSession indicates an expected call of CreateAccessTokenSession.
func (mr *MockStorageMockRecorder) CreateAccessTokenSession(ctx, signature, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessTokenSession", reflect.TypeOf((*MockStorage)(nil).CreateAccessTokenSession), ctx, signature, request)
}

// CreateAuthorizeCodeSession mocks base method.
func (m *MockStorage) CreateAuthorizeCodeSession(ctx context.Context, code string, request fosite.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthorizeCodeSession", ctx, code, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuthorizeCodeSession indicates an expected call of CreateAuthorizeCodeSession.
func (mr *MockStorageMockRecorder) CreateAuthorizeCodeSession(ctx, code, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthorizeCodeSession", reflect.TypeOf((*MockStorage)(nil).CreateAuthorizeCodeSession), ctx, code, request)
}

// CreatePKCERequestSession mocks base method.
func (m *MockStorage) CreatePKCERequestSession(ctx context.Context, signature string, requester fosite.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePKCERequestSession", ctx, signature, requester)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePKCERequestSession indicates an expected call of CreatePKCERequestSession.
func (mr *MockStorageMockRecorder) CreatePKCERequestSession(ctx, signature, requester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePKCERequestSession", reflect.TypeOf((*MockStorage)(nil).CreatePKCERequestSession), ctx, signature, requester)
}

// CreateRefreshTokenSession mocks base method.
func (m *MockStorage) CreateRefreshTokenSession(ctx context.Context, signature, accessSignature string, request fosite.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshTokenSession", ctx, signature, accessSignature, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshTokenSession indicates an expected call of CreateRefreshTokenSession.
func (mr *MockStorageMockRecorder) CreateRefreshTokenSession(ctx, signature, accessSignature, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshTokenSession", reflect.TypeOf((*MockStorage)(nil).CreateRefreshTokenSession), ctx, signature, accessSignature, request)
}

// DeleteAccessTokenSession mocks base method.
func (m *MockStorage) DeleteAccessTokenSession(ctx context.Context, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessTokenSession", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessTokenSession indicates an expected call of DeleteAccessTokenSession.
func (mr *MockStorageMockRecorder) DeleteAccessTokenSession(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessTokenSession", reflect.TypeOf((*MockStorage)(nil).DeleteAccessTokenSession), ctx, signature)
}

// DeleteIDPTokens mocks base method.
func (m *MockStorage) DeleteIDPTokens(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIDPTokens", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIDPTokens indicates an expected call of DeleteIDPTokens.
func (mr *MockStorageMockRecorder) DeleteIDPTokens(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIDPTokens", reflect.TypeOf((*MockStorage)(nil).DeleteIDPTokens), ctx, sessionID)
}

// DeletePKCERequestSession mocks base method.
func (m *MockStorage) DeletePKCERequestSession(ctx context.Context, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePKCERequestSession", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePKCERequestSession indicates an expected call of DeletePKCERequestSession.
func (mr *MockStorageMockRecorder) DeletePKCERequestSession(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePKCERequestSession", reflect.TypeOf((*MockStorage)(nil).DeletePKCERequestSession), ctx, signature)
}

// DeletePendingAuthorization mocks base method.
func (m *MockStorage) DeletePendingAuthorization(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingAuthorization", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingAuthorization indicates an expected call of DeletePendingAuthorization.
func (mr *MockStorageMockRecorder) DeletePendingAuthorization(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingAuthorization", reflect.TypeOf((*MockStorage)(nil).DeletePendingAuthorization), ctx, state)
}

// DeleteRefreshTokenSession mocks base method.
func (m *MockStorage) DeleteRefreshTokenSession(ctx context.Context, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshTokenSession", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshTokenSession indicates an expected call of DeleteRefreshTokenSession.
func (mr *MockStorageMockRecorder) DeleteRefreshTokenSession(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshTokenSession", reflect.TypeOf((*MockStorage)(nil).DeleteRefreshTokenSession), ctx, signature)
}

// GetAccessTokenSession mocks base method.
func (m *MockStorage) GetAccessTokenSession(ctx context.Context, signature string, session fosite.Session) (fosite.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenSession", ctx, signature, session)
	ret0, _ := ret[0].(fosite.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenSession indicates an expected call of GetAccessTokenSession.
func (mr *MockStorageMockRecorder) GetAccessTokenSession(ctx, signature, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenSession", reflect.TypeOf((*MockStorage)(nil).GetAccessTokenSession), ctx, signature, session)
}

// GetAuthorizeCodeSession mocks base method.
func (m *MockStorage) GetAuthorizeCodeSession(ctx context.Context, code string, session fosite.Session) (fosite.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizeCodeSession", ctx, code, session)
	ret0, _ := ret[0].(fosite.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizeCodeSession indicates an expected call of GetAuthorizeCodeSession.
func (mr *MockStorageMockRecorder) GetAuthorizeCodeSession(ctx, code, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizeCodeSession", reflect.TypeOf((*MockStorage)(nil).GetAuthorizeCodeSession), ctx, code, session)
}

// GetClient mocks base method.
func (m *MockStorage) GetClient(ctx context.Context, id string) (fosite.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, id)
	ret0, _ := ret[0].(fosite.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockStorageMockRecorder) GetClient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockStorage)(nil).GetClient), ctx, id)
}

// GetIDPTokens mocks base method.
func (m *MockStorage) GetIDPTokens(ctx context.Context, sessionID string) (*storage.IDPTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDPTokens", ctx, sessionID)
	ret0, _ := ret[0].(*storage.IDPTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDPTokens indicates an expected call of GetIDPTokens.
func (mr *MockStorageMockRecorder) GetIDPTokens(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDPTokens", reflect.TypeOf((*MockStorage)(nil).GetIDPTokens), ctx, sessionID)
}

// GetPKCERequestSession mocks base method.
func (m *MockStorage) GetPKCERequestSession(ctx context.Context, signature string, session fosite.Session) (fosite.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPKCERequestSession", ctx, signature, session)
	ret0, _ := ret[0].(fosite.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPKCERequestSession indicates an expected call of GetPKCERequestSession.
func (mr *MockStorageMockRecorder) GetPKCERequestSession(ctx, signature, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPKCERequestSession", reflect.TypeOf((*MockStorage)(nil).GetPKCERequestSession), ctx, signature, session)
}

// GetRefreshTokenSession mocks base method.
func (m *MockStorage) GetRefreshTokenSession(ctx context.Context, signature string, session fosite.Session) (fosite.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenSession", ctx, signature, session)
	ret0, _ := ret[0].(fosite.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenSession indicates an expected call of GetRefreshTokenSession.
func (mr *MockStorageMockRecorder) GetRefreshTokenSession(ctx, signature, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenSession", reflect.TypeOf((*MockStorage)(nil).GetRefreshTokenSession), ctx, signature, session)
}

// InvalidateAuthorizeCodeSession mocks base method.
func (m *MockStorage) InvalidateAuthorizeCodeSession(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAuthorizeCodeSession", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAuthorizeCodeSession indicates an expected call of InvalidateAuthorizeCodeSession.
func (mr *MockStorageMockRecorder) InvalidateAuthorizeCodeSession(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAuthorizeCodeSession", reflect.TypeOf((*MockStorage)(nil).InvalidateAuthorizeCodeSession), ctx, code)
}

// LoadPendingAuthorization mocks base method.
func (m *MockStorage) LoadPendingAuthorization(ctx context.Context, state string) (*storage.PendingAuthorization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPendingAuthorization", ctx, state)
	ret0, _ := ret[0].(*storage.PendingAuthorization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPendingAuthorization indicates an expected call of LoadPendingAuthorization.
func (mr *MockStorageMockRecorder) LoadPendingAuthorization(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPendingAuthorization", reflect.TypeOf((*MockStorage)(nil).LoadPendingAuthorization), ctx, state)
}

// RegisterClient mocks base method.
func (m *MockStorage) RegisterClient(ctx context.Context, client fosite.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterClient", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockStorageMockRecorder) RegisterClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockStorage)(nil).RegisterClient), ctx, client)
}

// RotateRefreshToken mocks base method.
func (m *MockStorage) RotateRefreshToken(ctx context.Context, requestID, refreshTokenSignature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, requestID, refreshTokenSignature)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockStorageMockRecorder) RotateRefreshToken(ctx, requestID, refreshTokenSignature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockStorage)(nil).RotateRefreshToken), ctx, requestID, refreshTokenSignature)
}

// SetClientAssertionJWT mocks base method.
func (m *MockStorage) SetClientAssertionJWT(ctx context.Context, jti string, exp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClientAssertionJWT", ctx, jti, exp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClientAssertionJWT indicates an expected call of SetClientAssertionJWT.
func (mr *MockStorageMockRecorder) SetClientAssertionJWT(ctx, jti, exp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClientAssertionJWT", reflect.TypeOf((*MockStorage)(nil).SetClientAssertionJWT), ctx, jti, exp)
}

// StoreIDPTokens mocks base method.
func (m *MockStorage) StoreIDPTokens(ctx context.Context, sessionID string, tokens *storage.IDPTokens) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreIDPTokens", ctx, sessionID, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreIDPTokens indicates an expected call of StoreIDPTokens.
func (mr *MockStorageMockRecorder) StoreIDPTokens(ctx, sessionID, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreIDPTokens", reflect.TypeOf((*MockStorage)(nil).StoreIDPTokens), ctx, sessionID, tokens)
}

// StorePendingAuthorization mocks base method.
func (m *MockStorage) StorePendingAuthorization(ctx context.Context, state string, pending *storage.PendingAuthorization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePendingAuthorization", ctx, state, pending)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePendingAuthorization indicates an expected call of StorePendingAuthorization.
func (mr *MockStorageMockRecorder) StorePendingAuthorization(ctx, state, pending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePendingAuthorization", reflect.TypeOf((*MockStorage)(nil).StorePendingAuthorization), ctx, state, pending)
}

// MockIDPTokenStorage is a mock of IDPTokenStorage interface.
type MockIDPTokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIDPTokenStorageMockRecorder
	isgomock struct{}
}

// MockIDPTokenStorageMockRecorder is the mock recorder for MockIDPTokenStorage.
type MockIDPTokenStorageMockRecorder struct {
	mock *MockIDPTokenStorage
}

// NewMockIDPTokenStorage creates a new mock instance.
func NewMockIDPTokenStorage(ctrl *gomock.Controller) *MockIDPTokenStorage {
	mock := &MockIDPTokenStorage{ctrl: ctrl}
	mock.recorder = &MockIDPTokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDPTokenStorage) EXPECT() *MockIDPTokenStorageMockRecorder {
	return m.recorder
}

// DeleteIDPTokens mocks base method.
func (m *MockIDPTokenStorage) DeleteIDPTokens(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIDPTokens", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIDPTokens indicates an expected call of DeleteIDPTokens.
func (mr *MockIDPTokenStorageMockRecorder) DeleteIDPTokens(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIDPTokens", reflect.TypeOf((*MockIDPTokenStorage)(nil).DeleteIDPTokens), ctx, sessionID)
}

// GetIDPTokens mocks base method.
func (m *MockIDPTokenStorage) GetIDPTokens(ctx context.Context, sessionID string) (*storage.IDPTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDPTokens", ctx, sessionID)
	ret0, _ := ret[0].(*storage.IDPTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDPTokens indicates an expected call of GetIDPTokens.
func (mr *MockIDPTokenStorageMockRecorder) GetIDPTokens(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDPTokens", reflect.TypeOf((*MockIDPTokenStorage)(nil).GetIDPTokens), ctx, sessionID)
}

// StoreIDPTokens mocks base method.
func (m *MockIDPTokenStorage) StoreIDPTokens(ctx context.Context, sessionID string, tokens *storage.IDPTokens) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreIDPTokens", ctx, sessionID, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreIDPTokens indicates an expected call of StoreIDPTokens.
func (mr *MockIDPTokenStorageMockRecorder) StoreIDPTokens(ctx, sessionID, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreIDPTokens", reflect.TypeOf((*MockIDPTokenStorage)(nil).StoreIDPTokens), ctx, sessionID, tokens)
}
