// Code generated by MockGen. DO NOT EDIT.
// Source: verifier.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_verifier.go -package=mocks -source=verifier.go Verifier,OCISnapshotVerifier,OCISnapshot
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	lockfile "github.com/stacklok/toolhive/pkg/skills/lockfile"
	verifier "github.com/stacklok/toolhive/pkg/skills/verifier"
	gomock "go.uber.org/mock/gomock"
)

// MockVerifier is a mock of Verifier interface.
type MockVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockVerifierMockRecorder
	isgomock struct{}
}

// MockVerifierMockRecorder is the mock recorder for MockVerifier.
type MockVerifierMockRecorder struct {
	mock *MockVerifier
}

// NewMockVerifier creates a new mock instance.
func NewMockVerifier(ctrl *gomock.Controller) *MockVerifier {
	mock := &MockVerifier{ctrl: ctrl}
	mock.recorder = &MockVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifier) EXPECT() *MockVerifierMockRecorder {
	return m.recorder
}

// ResultFromBundle mocks base method.
func (m *MockVerifier) ResultFromBundle(bundle []byte, digest string) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResultFromBundle", bundle, digest)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResultFromBundle indicates an expected call of ResultFromBundle.
func (mr *MockVerifierMockRecorder) ResultFromBundle(bundle, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResultFromBundle", reflect.TypeOf((*MockVerifier)(nil).ResultFromBundle), bundle, digest)
}

// VerifyBundleOffline mocks base method.
func (m *MockVerifier) VerifyBundleOffline(bundle []byte, digest string, expected *lockfile.Provenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyBundleOffline", bundle, digest, expected)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyBundleOffline indicates an expected call of VerifyBundleOffline.
func (mr *MockVerifierMockRecorder) VerifyBundleOffline(bundle, digest, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyBundleOffline", reflect.TypeOf((*MockVerifier)(nil).VerifyBundleOffline), bundle, digest, expected)
}

// VerifyBundleOfflineWithKey mocks base method.
func (m *MockVerifier) VerifyBundleOfflineWithKey(bundle []byte, digest string, pubKeyPEM []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyBundleOfflineWithKey", bundle, digest, pubKeyPEM)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyBundleOfflineWithKey indicates an expected call of VerifyBundleOfflineWithKey.
func (mr *MockVerifierMockRecorder) VerifyBundleOfflineWithKey(bundle, digest, pubKeyPEM any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyBundleOfflineWithKey", reflect.TypeOf((*MockVerifier)(nil).VerifyBundleOfflineWithKey), bundle, digest, pubKeyPEM)
}

// VerifyGit mocks base method.
func (m *MockVerifier) VerifyGit(ctx context.Context, payload, signature []byte, expected *verifier.ProvenanceExpectation) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyGit", ctx, payload, signature, expected)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyGit indicates an expected call of VerifyGit.
func (mr *MockVerifierMockRecorder) VerifyGit(ctx, payload, signature, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyGit", reflect.TypeOf((*MockVerifier)(nil).VerifyGit), ctx, payload, signature, expected)
}

// VerifyOCI mocks base method.
func (m *MockVerifier) VerifyOCI(ctx context.Context, imageRef, digest string, expected *verifier.ProvenanceExpectation) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOCI", ctx, imageRef, digest, expected)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOCI indicates an expected call of VerifyOCI.
func (mr *MockVerifierMockRecorder) VerifyOCI(ctx, imageRef, digest, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOCI", reflect.TypeOf((*MockVerifier)(nil).VerifyOCI), ctx, imageRef, digest, expected)
}

// VerifyOCIWithKey mocks base method.
func (m *MockVerifier) VerifyOCIWithKey(ctx context.Context, imageRef, digest string, pubKeyPEM []byte) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOCIWithKey", ctx, imageRef, digest, pubKeyPEM)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOCIWithKey indicates an expected call of VerifyOCIWithKey.
func (mr *MockVerifierMockRecorder) VerifyOCIWithKey(ctx, imageRef, digest, pubKeyPEM any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOCIWithKey", reflect.TypeOf((*MockVerifier)(nil).VerifyOCIWithKey), ctx, imageRef, digest, pubKeyPEM)
}

// MockOCISnapshotRetriever is a mock of OCISnapshotRetriever interface.
type MockOCISnapshotRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockOCISnapshotRetrieverMockRecorder
	isgomock struct{}
}

// MockOCISnapshotRetrieverMockRecorder is the mock recorder for MockOCISnapshotRetriever.
type MockOCISnapshotRetrieverMockRecorder struct {
	mock *MockOCISnapshotRetriever
}

// NewMockOCISnapshotRetriever creates a new mock instance.
func NewMockOCISnapshotRetriever(ctrl *gomock.Controller) *MockOCISnapshotRetriever {
	mock := &MockOCISnapshotRetriever{ctrl: ctrl}
	mock.recorder = &MockOCISnapshotRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCISnapshotRetriever) EXPECT() *MockOCISnapshotRetrieverMockRecorder {
	return m.recorder
}

// RetrieveOCISnapshot mocks base method.
func (m *MockOCISnapshotRetriever) RetrieveOCISnapshot(ctx context.Context, imageRef, digest string) (verifier.OCISnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveOCISnapshot", ctx, imageRef, digest)
	ret0, _ := ret[0].(verifier.OCISnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveOCISnapshot indicates an expected call of RetrieveOCISnapshot.
func (mr *MockOCISnapshotRetrieverMockRecorder) RetrieveOCISnapshot(ctx, imageRef, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveOCISnapshot", reflect.TypeOf((*MockOCISnapshotRetriever)(nil).RetrieveOCISnapshot), ctx, imageRef, digest)
}

// MockOCISnapshotVerifier is a mock of OCISnapshotVerifier interface.
type MockOCISnapshotVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockOCISnapshotVerifierMockRecorder
	isgomock struct{}
}

// MockOCISnapshotVerifierMockRecorder is the mock recorder for MockOCISnapshotVerifier.
type MockOCISnapshotVerifierMockRecorder struct {
	mock *MockOCISnapshotVerifier
}

// NewMockOCISnapshotVerifier creates a new mock instance.
func NewMockOCISnapshotVerifier(ctrl *gomock.Controller) *MockOCISnapshotVerifier {
	mock := &MockOCISnapshotVerifier{ctrl: ctrl}
	mock.recorder = &MockOCISnapshotVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCISnapshotVerifier) EXPECT() *MockOCISnapshotVerifierMockRecorder {
	return m.recorder
}

// ResultFromBundle mocks base method.
func (m *MockOCISnapshotVerifier) ResultFromBundle(bundle []byte, digest string) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResultFromBundle", bundle, digest)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResultFromBundle indicates an expected call of ResultFromBundle.
func (mr *MockOCISnapshotVerifierMockRecorder) ResultFromBundle(bundle, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResultFromBundle", reflect.TypeOf((*MockOCISnapshotVerifier)(nil).ResultFromBundle), bundle, digest)
}

// RetrieveOCISnapshot mocks base method.
func (m *MockOCISnapshotVerifier) RetrieveOCISnapshot(ctx context.Context, imageRef, digest string) (verifier.OCISnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveOCISnapshot", ctx, imageRef, digest)
	ret0, _ := ret[0].(verifier.OCISnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveOCISnapshot indicates an expected call of RetrieveOCISnapshot.
func (mr *MockOCISnapshotVerifierMockRecorder) RetrieveOCISnapshot(ctx, imageRef, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveOCISnapshot", reflect.TypeOf((*MockOCISnapshotVerifier)(nil).RetrieveOCISnapshot), ctx, imageRef, digest)
}

// VerifyBundleOffline mocks base method.
func (m *MockOCISnapshotVerifier) VerifyBundleOffline(bundle []byte, digest string, expected *lockfile.Provenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyBundleOffline", bundle, digest, expected)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyBundleOffline indicates an expected call of VerifyBundleOffline.
func (mr *MockOCISnapshotVerifierMockRecorder) VerifyBundleOffline(bundle, digest, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyBundleOffline", reflect.TypeOf((*MockOCISnapshotVerifier)(nil).VerifyBundleOffline), bundle, digest, expected)
}

// VerifyBundleOfflineWithKey mocks base method.
func (m *MockOCISnapshotVerifier) VerifyBundleOfflineWithKey(bundle []byte, digest string, pubKeyPEM []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyBundleOfflineWithKey", bundle, digest, pubKeyPEM)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyBundleOfflineWithKey indicates an expected call of VerifyBundleOfflineWithKey.
func (mr *MockOCISnapshotVerifierMockRecorder) VerifyBundleOfflineWithKey(bundle, digest, pubKeyPEM any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyBundleOfflineWithKey", reflect.TypeOf((*MockOCISnapshotVerifier)(nil).VerifyBundleOfflineWithKey), bundle, digest, pubKeyPEM)
}

// VerifyGit mocks base method.
func (m *MockOCISnapshotVerifier) VerifyGit(ctx context.Context, payload, signature []byte, expected *verifier.ProvenanceExpectation) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyGit", ctx, payload, signature, expected)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyGit indicates an expected call of VerifyGit.
func (mr *MockOCISnapshotVerifierMockRecorder) VerifyGit(ctx, payload, signature, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyGit", reflect.TypeOf((*MockOCISnapshotVerifier)(nil).VerifyGit), ctx, payload, signature, expected)
}

// VerifyOCI mocks base method.
func (m *MockOCISnapshotVerifier) VerifyOCI(ctx context.Context, imageRef, digest string, expected *verifier.ProvenanceExpectation) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOCI", ctx, imageRef, digest, expected)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOCI indicates an expected call of VerifyOCI.
func (mr *MockOCISnapshotVerifierMockRecorder) VerifyOCI(ctx, imageRef, digest, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOCI", reflect.TypeOf((*MockOCISnapshotVerifier)(nil).VerifyOCI), ctx, imageRef, digest, expected)
}

// VerifyOCIWithKey mocks base method.
func (m *MockOCISnapshotVerifier) VerifyOCIWithKey(ctx context.Context, imageRef, digest string, pubKeyPEM []byte) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOCIWithKey", ctx, imageRef, digest, pubKeyPEM)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOCIWithKey indicates an expected call of VerifyOCIWithKey.
func (mr *MockOCISnapshotVerifierMockRecorder) VerifyOCIWithKey(ctx, imageRef, digest, pubKeyPEM any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOCIWithKey", reflect.TypeOf((*MockOCISnapshotVerifier)(nil).VerifyOCIWithKey), ctx, imageRef, digest, pubKeyPEM)
}

// MockOCISnapshot is a mock of OCISnapshot interface.
type MockOCISnapshot struct {
	ctrl     *gomock.Controller
	recorder *MockOCISnapshotMockRecorder
	isgomock struct{}
}

// MockOCISnapshotMockRecorder is the mock recorder for MockOCISnapshot.
type MockOCISnapshotMockRecorder struct {
	mock *MockOCISnapshot
}

// NewMockOCISnapshot creates a new mock instance.
func NewMockOCISnapshot(ctrl *gomock.Controller) *MockOCISnapshot {
	mock := &MockOCISnapshot{ctrl: ctrl}
	mock.recorder = &MockOCISnapshotMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCISnapshot) EXPECT() *MockOCISnapshotMockRecorder {
	return m.recorder
}

// VerifyKeyless mocks base method.
func (m *MockOCISnapshot) VerifyKeyless(expected *verifier.ProvenanceExpectation) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyKeyless", expected)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyKeyless indicates an expected call of VerifyKeyless.
func (mr *MockOCISnapshotMockRecorder) VerifyKeyless(expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyKeyless", reflect.TypeOf((*MockOCISnapshot)(nil).VerifyKeyless), expected)
}

// VerifyWithKey mocks base method.
func (m *MockOCISnapshot) VerifyWithKey(pubKeyPEM []byte) (*verifier.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWithKey", pubKeyPEM)
	ret0, _ := ret[0].(*verifier.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyWithKey indicates an expected call of VerifyWithKey.
func (mr *MockOCISnapshotMockRecorder) VerifyWithKey(pubKeyPEM any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWithKey", reflect.TypeOf((*MockOCISnapshot)(nil).VerifyWithKey), pubKeyPEM)
}
