# Invalid Virtual MCP Server Configuration Example
# This file has intentional errors to test validation

# Missing required field: name
# name: "test-vmcp"
group: "test-group"

# Invalid auth type
incoming_auth:
  type: invalid_type
  oidc:
    issuer: "https://keycloak.example.com"
    client_id: "test-client"
    client_secret_env: "TEST_SECRET"
    audience: "vmcp"
    scopes: ["openid"]

# Invalid source
outgoing_auth:
  source: invalid_source
  default:
    type: pass_through

# Invalid conflict resolution strategy
aggregation:
  conflict_resolution: invalid_strategy
  conflict_resolution_config:
    prefix_format: "{workload}_"
