// SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0

package webhook

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/stacklok/toolhive/pkg/config"
	"github.com/stacklok/toolhive/pkg/secrets"
)

// ResolveSecret resolves a webhook secret reference using the active secrets provider.
// It accepts either a raw secret name or CLI-style "<name>,target=<target>" format.
func ResolveSecret(ctx context.Context, ref string) ([]byte, error) {
	if ref == "" {
		return nil, nil
	}

	if filepath.IsAbs(ref) {
		// #nosec G304 -- absolute refs are generated by the operator for mounted webhook Secret files.
		value, err := os.ReadFile(ref)
		if err != nil {
			return nil, fmt.Errorf("failed to read webhook secret file %q: %w", ref, err)
		}
		return value, nil
	}

	secretName := ref
	// Raw secret names are also valid references, so parse errors intentionally fall back to ref as-is.
	if secretParam, err := secrets.ParseSecretParameter(ref); err == nil {
		secretName = secretParam.Name
	}

	provider, err := resolveSecretProvider()
	if err != nil {
		return nil, fmt.Errorf("failed to initialize webhook secrets provider: %w", err)
	}

	value, err := provider.GetSecret(ctx, secretName)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve webhook secret %q: %w", secretName, err)
	}

	return []byte(value), nil
}

func resolveSecretProvider() (secrets.Provider, error) {
	if providerType := os.Getenv(secrets.ProviderEnvVar); providerType != "" {
		return secrets.CreateSecretProvider(secrets.ProviderType(providerType))
	}

	cfg := config.NewDefaultProvider().GetConfig()
	if !cfg.Secrets.SetupCompleted {
		return nil, secrets.ErrSecretsNotSetup
	}

	providerType, err := cfg.Secrets.GetProviderType()
	if err != nil {
		return nil, fmt.Errorf("failed to get configured secrets provider type: %w", err)
	}

	return secrets.CreateProvider(providerType, secrets.WithUserFacing())
}
