// SPDX-FileCopyrightText: Copyright 2026 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0

package proxy

import (
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"github.com/adrg/xdg"

	"github.com/stacklok/toolhive/pkg/process"
)

func pidFilePath() (string, error) {
	return xdg.DataFile("toolhive/llm-proxy.pid")
}

// LogFilePath returns the XDG data path for the LLM proxy log file.
// Exported so CLI commands can display the path to the user.
func LogFilePath() (string, error) {
	return xdg.DataFile("toolhive/logs/llm-proxy.log")
}

// IsRunning checks whether the LLM proxy is currently running.
func IsRunning() (bool, int, error) {
	pidPath, err := pidFilePath()
	if err != nil {
		return false, 0, fmt.Errorf("resolving PID file path: %w", err)
	}
	return isRunningAt(pidPath)
}

// isRunningAt checks liveness using an explicit PID file path.
// Used directly by tests to avoid mutating shared state.
func isRunningAt(pidPath string) (bool, int, error) {
	data, err := os.ReadFile(pidPath) // #nosec G304 — path is generated by xdg from application constants
	if errors.Is(err, os.ErrNotExist) {
		return false, 0, nil
	}
	if err != nil {
		return false, 0, fmt.Errorf("reading PID file: %w", err)
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return false, 0, fmt.Errorf("parsing PID file: %w", err)
	}
	alive, err := process.FindProcess(pid)
	if err != nil {
		return false, 0, fmt.Errorf("checking process liveness: %w", err)
	}
	return alive, pid, nil
}

// Stop sends SIGTERM to the running proxy and removes the PID file.
func Stop() error {
	pidPath, err := pidFilePath()
	if err != nil {
		return fmt.Errorf("resolving PID file path: %w", err)
	}
	return stopAt(pidPath)
}

// stopAt stops the proxy using an explicit PID file path.
// Used directly by tests to avoid mutating shared state.
func stopAt(pidPath string) error {
	running, pid, err := isRunningAt(pidPath)
	if err != nil {
		return err
	}
	if !running {
		return errors.New("LLM proxy is not running")
	}

	if err := process.KillProcess(pid); err != nil {
		return fmt.Errorf("stopping process %d: %w", pid, err)
	}

	if err := os.Remove(pidPath); err != nil && !errors.Is(err, os.ErrNotExist) {
		slog.Warn("failed to remove LLM proxy PID file", "path", pidPath, "error", err)
	}
	return nil
}

// StartDetached launches the current binary as a detached background process.
func StartDetached(execPath string, debug bool) (int, error) {
	pidPath, err := pidFilePath()
	if err != nil {
		return 0, fmt.Errorf("resolving PID file path: %w", err)
	}
	logPath, err := LogFilePath()
	if err != nil {
		return 0, fmt.Errorf("resolving log file path: %w", err)
	}
	return startDetachedAt(pidPath, logPath, execPath, debug)
}

// startDetachedAt launches a detached process using explicit file paths.
// Used directly by tests to avoid mutating shared state.
func startDetachedAt(pidPath, logPath, execPath string, debug bool) (int, error) {
	running, pid, err := isRunningAt(pidPath)
	if err != nil {
		return 0, err
	}
	if running {
		return 0, fmt.Errorf("LLM proxy is already running (PID %d)", pid)
	}

	// #nosec G304
	logFile, err := os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0600)
	if err != nil {
		slog.Warn("LLM proxy: could not open log file, output will be discarded",
			"path", logPath, "error", err)
	} else {
		defer func() {
			if closeErr := logFile.Close(); closeErr != nil {
				slog.Warn("failed to close LLM proxy log file", "error", closeErr)
			}
		}()
	}

	args := []string{"llm", "proxy", "start", "--foreground"}
	if debug {
		args = append(args, "--debug")
	}

	// #nosec G204
	cmd := exec.Command(execPath, args...)
	cmd.Env = append(os.Environ(),
		fmt.Sprintf("%s=%s", process.ToolHiveDetachedEnv, process.ToolHiveDetachedValue),
	)
	cmd.SysProcAttr = getSysProcAttr()

	if logFile != nil {
		cmd.Stdout = logFile
		cmd.Stderr = logFile
	}

	if err := cmd.Start(); err != nil {
		return 0, fmt.Errorf("starting LLM proxy process: %w", err)
	}

	childPID := cmd.Process.Pid

	if err := os.WriteFile(pidPath, []byte(strconv.Itoa(childPID)), 0600); err != nil {
		// Kill the child so it doesn't run unmanaged without a PID file.
		if killErr := cmd.Process.Kill(); killErr != nil {
			slog.Warn("failed to kill orphaned LLM proxy process", "pid", childPID, "error", killErr)
		}
		return 0, fmt.Errorf("writing PID file: %w", err)
	}

	return childPID, nil
}
