// Code generated by MockGen. DO NOT EDIT.
// Source: skillsvc.go
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_skill_lookup.go -package=mocks -source=skillsvc.go SkillLookup
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	registry "github.com/stacklok/toolhive-core/registry/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSkillLookup is a mock of SkillLookup interface.
type MockSkillLookup struct {
	ctrl     *gomock.Controller
	recorder *MockSkillLookupMockRecorder
	isgomock struct{}
}

// MockSkillLookupMockRecorder is the mock recorder for MockSkillLookup.
type MockSkillLookupMockRecorder struct {
	mock *MockSkillLookup
}

// NewMockSkillLookup creates a new mock instance.
func NewMockSkillLookup(ctrl *gomock.Controller) *MockSkillLookup {
	mock := &MockSkillLookup{ctrl: ctrl}
	mock.recorder = &MockSkillLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillLookup) EXPECT() *MockSkillLookupMockRecorder {
	return m.recorder
}

// SearchSkills mocks base method.
func (m *MockSkillLookup) SearchSkills(query string) ([]registry.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSkills", query)
	ret0, _ := ret[0].([]registry.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSkills indicates an expected call of SearchSkills.
func (mr *MockSkillLookupMockRecorder) SearchSkills(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSkills", reflect.TypeOf((*MockSkillLookup)(nil).SearchSkills), query)
}
