// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_path_resolver.go -package=mocks -source=types.go PathResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	skills "github.com/stacklok/toolhive/pkg/skills"
	gomock "go.uber.org/mock/gomock"
)

// MockPathResolver is a mock of PathResolver interface.
type MockPathResolver struct {
	ctrl     *gomock.Controller
	recorder *MockPathResolverMockRecorder
	isgomock struct{}
}

// MockPathResolverMockRecorder is the mock recorder for MockPathResolver.
type MockPathResolverMockRecorder struct {
	mock *MockPathResolver
}

// NewMockPathResolver creates a new mock instance.
func NewMockPathResolver(ctrl *gomock.Controller) *MockPathResolver {
	mock := &MockPathResolver{ctrl: ctrl}
	mock.recorder = &MockPathResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPathResolver) EXPECT() *MockPathResolverMockRecorder {
	return m.recorder
}

// GetSkillPath mocks base method.
func (m *MockPathResolver) GetSkillPath(clientType, skillName string, scope skills.Scope, projectRoot string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillPath", clientType, skillName, scope, projectRoot)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillPath indicates an expected call of GetSkillPath.
func (mr *MockPathResolverMockRecorder) GetSkillPath(clientType, skillName, scope, projectRoot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillPath", reflect.TypeOf((*MockPathResolver)(nil).GetSkillPath), clientType, skillName, scope, projectRoot)
}

// ListSkillSupportingClients mocks base method.
func (m *MockPathResolver) ListSkillSupportingClients() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkillSupportingClients")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListSkillSupportingClients indicates an expected call of ListSkillSupportingClients.
func (mr *MockPathResolverMockRecorder) ListSkillSupportingClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkillSupportingClients", reflect.TypeOf((*MockPathResolver)(nil).ListSkillSupportingClients))
}
