# Example: VirtualMCPServer with Optimizer Auto-Configured via EmbeddingServerRef
#
# This example demonstrates a VirtualMCPServer that automatically enables the
# optimizer feature by simply referencing an EmbeddingServer. When embeddingServerRef
# is set without an explicit optimizer config, the operator auto-populates the
# optimizer with default values and emits an "OptimizerAutoConfigured" event.
#
# When the optimizer is enabled, vMCP exposes only two meta-tools to clients:
#   - find_tool: Search for tools by natural language description
#   - call_tool: Invoke a discovered tool by name
#
# This reduces token usage for LLMs by avoiding sending all tool definitions
# upfront, instead allowing on-demand tool discovery.
#
# This example creates:
# 1. An MCPGroup to organize backends
# 2. A yardstick MCPServer backend
# 3. A fetch MCPServer backend (URL fetching)
# 4. An EmbeddingServer for the optimizer (using all default values)
# 5. A VirtualMCPServer with optimizer auto-configured via embeddingServerRef
#
# Apple Silicon (ARM64) Note:
#   The embedding server image (ghcr.io/huggingface/text-embeddings-inference:cpu-latest)
#   is amd64-only. On ARM64 Macs with Kind, you must pre-load it:
#     docker pull --platform linux/amd64 ghcr.io/huggingface/text-embeddings-inference:cpu-latest
#     kind load docker-image ghcr.io/huggingface/text-embeddings-inference:cpu-latest --name toolhive
#   ARM64 support is tracked in: https://github.com/huggingface/text-embeddings-inference/pull/827
#
# Usage:
#   kubectl apply -f vmcp_optimizer_example.yaml

---
# Step 1: Create MCPGroup
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPGroup
metadata:
  name: optimizer-services
  namespace: default
spec:
  description: Backend services for optimizer-enabled VirtualMCPServer

---
# Step 2: Create MCPServer backend - yardstick
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: yardstick
  namespace: default
spec:
  groupRef: optimizer-services
  image: ghcr.io/stackloklabs/yardstick/yardstick-server:1.1.1
  transport: stdio
  proxyPort: 8080
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

---
# Step 3: Create MCPServer backend - fetch (URL content fetching)
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: fetch
  namespace: default
spec:
  groupRef: optimizer-services
  image: ghcr.io/stackloklabs/gofetch/server
  transport: streamable-http
  proxyPort: 8080
  mcpPort: 8080
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

---
# Step 4: Create EmbeddingServer for the optimizer
# All fields use kubebuilder defaults:
#   model: BAAI/bge-small-en-v1.5
#   image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
#   port: 8080
#   imagePullPolicy: IfNotPresent
#   replicas: 1
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: optimizer-embedding
  namespace: default
spec: {}

---
# Step 5: Create VirtualMCPServer with optimizer auto-configured
# Note: No explicit "optimizer" config is needed. The operator detects that
# embeddingServerRef is set, auto-populates the optimizer with default values,
# resolves the EmbeddingServer URL, and emits an "OptimizerAutoConfigured" event.
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: optimizer-vmcp
  namespace: default
spec:
  config:
    groupRef: optimizer-services

    # Aggregation: prefix strategy prevents tool name conflicts
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"

    # No optimizer config needed — auto-configured from embeddingServerRef below.

    # Operational settings
    operational:
      failureHandling:
        healthCheckInterval: 30s

  # Incoming authentication (client -> vMCP)
  # Anonymous auth for easy local testing
  incomingAuth:
    type: anonymous
    authzConfig:
      type: inline
      inline:
        policies:
          - 'permit(principal, action, resource);'

  # Reference to a shared EmbeddingServer.
  # When embeddingServerRef is set without an explicit optimizer config, the operator
  # auto-populates the optimizer with default values and resolves the URL automatically.
  embeddingServerRef:
    name: optimizer-embedding

  # Outgoing authentication (vMCP -> backends)
  # Discovered mode auto-discovers auth from backend MCPServers
  outgoingAuth:
    source: discovered
