// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/toolhive/pkg/vmcp/auth/resolver (interfaces: AuthResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_auth_resolver.go -package=mocks github.com/stacklok/toolhive/pkg/vmcp/auth/resolver AuthResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/stacklok/toolhive/pkg/vmcp/auth/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthResolver is a mock of AuthResolver interface.
type MockAuthResolver struct {
	ctrl     *gomock.Controller
	recorder *MockAuthResolverMockRecorder
	isgomock struct{}
}

// MockAuthResolverMockRecorder is the mock recorder for MockAuthResolver.
type MockAuthResolverMockRecorder struct {
	mock *MockAuthResolver
}

// NewMockAuthResolver creates a new mock instance.
func NewMockAuthResolver(ctrl *gomock.Controller) *MockAuthResolver {
	mock := &MockAuthResolver{ctrl: ctrl}
	mock.recorder = &MockAuthResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthResolver) EXPECT() *MockAuthResolverMockRecorder {
	return m.recorder
}

// ResolveExternalAuthConfig mocks base method.
func (m *MockAuthResolver) ResolveExternalAuthConfig(ctx context.Context, refName string) (*types.BackendAuthStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveExternalAuthConfig", ctx, refName)
	ret0, _ := ret[0].(*types.BackendAuthStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveExternalAuthConfig indicates an expected call of ResolveExternalAuthConfig.
func (mr *MockAuthResolverMockRecorder) ResolveExternalAuthConfig(ctx, refName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveExternalAuthConfig", reflect.TypeOf((*MockAuthResolver)(nil).ResolveExternalAuthConfig), ctx, refName)
}
