// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_adapter.go -package=mocks -source=adapter.go MaterializationAdapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	plugins "github.com/stacklok/toolhive/pkg/plugins"
	gomock "go.uber.org/mock/gomock"
)

// MockMaterializationAdapter is a mock of MaterializationAdapter interface.
type MockMaterializationAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockMaterializationAdapterMockRecorder
	isgomock struct{}
}

// MockMaterializationAdapterMockRecorder is the mock recorder for MockMaterializationAdapter.
type MockMaterializationAdapterMockRecorder struct {
	mock *MockMaterializationAdapter
}

// NewMockMaterializationAdapter creates a new mock instance.
func NewMockMaterializationAdapter(ctrl *gomock.Controller) *MockMaterializationAdapter {
	mock := &MockMaterializationAdapter{ctrl: ctrl}
	mock.recorder = &MockMaterializationAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaterializationAdapter) EXPECT() *MockMaterializationAdapterMockRecorder {
	return m.recorder
}

// DegradesOnProjectScope mocks base method.
func (m *MockMaterializationAdapter) DegradesOnProjectScope() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DegradesOnProjectScope")
	ret0, _ := ret[0].(bool)
	return ret0
}

// DegradesOnProjectScope indicates an expected call of DegradesOnProjectScope.
func (mr *MockMaterializationAdapterMockRecorder) DegradesOnProjectScope() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DegradesOnProjectScope", reflect.TypeOf((*MockMaterializationAdapter)(nil).DegradesOnProjectScope))
}

// Dematerialize mocks base method.
func (m *MockMaterializationAdapter) Dematerialize(ctx context.Context, name string, scope plugins.Scope, projectRoot string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dematerialize", ctx, name, scope, projectRoot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dematerialize indicates an expected call of Dematerialize.
func (mr *MockMaterializationAdapterMockRecorder) Dematerialize(ctx, name, scope, projectRoot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dematerialize", reflect.TypeOf((*MockMaterializationAdapter)(nil).Dematerialize), ctx, name, scope, projectRoot)
}

// Materialize mocks base method.
func (m *MockMaterializationAdapter) Materialize(ctx context.Context, req plugins.MaterializeRequest) (*plugins.MaterializeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Materialize", ctx, req)
	ret0, _ := ret[0].(*plugins.MaterializeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Materialize indicates an expected call of Materialize.
func (mr *MockMaterializationAdapterMockRecorder) Materialize(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Materialize", reflect.TypeOf((*MockMaterializationAdapter)(nil).Materialize), ctx, req)
}

// SupportedComponents mocks base method.
func (m *MockMaterializationAdapter) SupportedComponents() []plugins.ComponentType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedComponents")
	ret0, _ := ret[0].([]plugins.ComponentType)
	return ret0
}

// SupportedComponents indicates an expected call of SupportedComponents.
func (mr *MockMaterializationAdapterMockRecorder) SupportedComponents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedComponents", reflect.TypeOf((*MockMaterializationAdapter)(nil).SupportedComponents))
}
