// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/toolhive/pkg/vmcp/session/untrusted (interfaces: PodLifecycle,BackendAddressResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_lifecycle.go -package=mocks github.com/stacklok/toolhive/pkg/vmcp/session/untrusted PodLifecycle,BackendAddressResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	vmcp "github.com/stacklok/toolhive/pkg/vmcp"
	untrusted "github.com/stacklok/toolhive/pkg/vmcp/session/untrusted"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockPodLifecycle is a mock of PodLifecycle interface.
type MockPodLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockPodLifecycleMockRecorder
	isgomock struct{}
}

// MockPodLifecycleMockRecorder is the mock recorder for MockPodLifecycle.
type MockPodLifecycleMockRecorder struct {
	mock *MockPodLifecycle
}

// NewMockPodLifecycle creates a new mock instance.
func NewMockPodLifecycle(ctrl *gomock.Controller) *MockPodLifecycle {
	mock := &MockPodLifecycle{ctrl: ctrl}
	mock.recorder = &MockPodLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodLifecycle) EXPECT() *MockPodLifecycleMockRecorder {
	return m.recorder
}

// DeletePod mocks base method.
func (m *MockPodLifecycle) DeletePod(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePod", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePod indicates an expected call of DeletePod.
func (mr *MockPodLifecycleMockRecorder) DeletePod(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePod", reflect.TypeOf((*MockPodLifecycle)(nil).DeletePod), ctx, name)
}

// EnsurePod mocks base method.
func (m *MockPodLifecycle) EnsurePod(ctx context.Context, req untrusted.EnsurePodRequest) (*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePod", ctx, req)
	ret0, _ := ret[0].(*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsurePod indicates an expected call of EnsurePod.
func (mr *MockPodLifecycleMockRecorder) EnsurePod(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePod", reflect.TypeOf((*MockPodLifecycle)(nil).EnsurePod), ctx, req)
}

// WaitReady mocks base method.
func (m *MockPodLifecycle) WaitReady(ctx context.Context, pod *v1.Pod, budget time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitReady", ctx, pod, budget)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitReady indicates an expected call of WaitReady.
func (mr *MockPodLifecycleMockRecorder) WaitReady(ctx, pod, budget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitReady", reflect.TypeOf((*MockPodLifecycle)(nil).WaitReady), ctx, pod, budget)
}

// MockBackendAddressResolver is a mock of BackendAddressResolver interface.
type MockBackendAddressResolver struct {
	ctrl     *gomock.Controller
	recorder *MockBackendAddressResolverMockRecorder
	isgomock struct{}
}

// MockBackendAddressResolverMockRecorder is the mock recorder for MockBackendAddressResolver.
type MockBackendAddressResolverMockRecorder struct {
	mock *MockBackendAddressResolver
}

// NewMockBackendAddressResolver creates a new mock instance.
func NewMockBackendAddressResolver(ctrl *gomock.Controller) *MockBackendAddressResolver {
	mock := &MockBackendAddressResolver{ctrl: ctrl}
	mock.recorder = &MockBackendAddressResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendAddressResolver) EXPECT() *MockBackendAddressResolverMockRecorder {
	return m.recorder
}

// ResolveTargets mocks base method.
func (m *MockBackendAddressResolver) ResolveTargets(ctx context.Context, sess untrusted.SessionRef, backends []*vmcp.Backend, onNewPod func(string)) []*vmcp.Backend {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTargets", ctx, sess, backends, onNewPod)
	ret0, _ := ret[0].([]*vmcp.Backend)
	return ret0
}

// ResolveTargets indicates an expected call of ResolveTargets.
func (mr *MockBackendAddressResolverMockRecorder) ResolveTargets(ctx, sess, backends, onNewPod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTargets", reflect.TypeOf((*MockBackendAddressResolver)(nil).ResolveTargets), ctx, sess, backends, onNewPod)
}
