# MCPEmbedding with MCPGroup association
# This example shows how to organize embeddings within a group

# First, create the MCPGroup
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPGroup
metadata:
  name: ml-services
  namespace: toolhive-system
spec:
  description: "Machine learning services for AI applications"
---
# Create an embedding server that belongs to the group
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPEmbedding
metadata:
  name: ml-embedding
  namespace: toolhive-system
spec:
  # Reference the MCPGroup
  groupRef: "ml-services"

  # Model configuration
  model: "sentence-transformers/all-MiniLM-L6-v2"
  image: "ghcr.io/huggingface/text-embeddings-inference:latest"
  port: 8080

  # Enable model caching
  modelCache:
    enabled: true
    size: "10Gi"

  # Resource limits
  resources:
    limits:
      cpu: "2000m"
      memory: "4Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
