// Code generated by ogen, DO NOT EDIT.

package client

// CheckWorkloadForUpgradeParams is parameters of CheckWorkloadForUpgrade operation.
type CheckWorkloadForUpgradeParams struct {
	// Workload name.
	Name string
}

// CheckWorkloadsForUpgradesParams is parameters of CheckWorkloadsForUpgrades operation.
type CheckWorkloadsForUpgradesParams struct {
	// Include stopped workloads.
	All OptBool
	// Filter workloads by group name.
	Group OptString
}

// DeleteDefaultSecretParams is parameters of DeleteDefaultSecret operation.
type DeleteDefaultSecretParams struct {
	// Secret key.
	Key string
}

// DeleteGroupParams is parameters of DeleteGroup operation.
type DeleteGroupParams struct {
	// Group name.
	Name string
	// Delete all workloads in the group (default: false, moves workloads to default group).
	WithWorkloads OptBool
}

// DeletePluginParams is parameters of DeletePlugin operation.
type DeletePluginParams struct {
	// Plugin name.
	Name string
	// Scope to uninstall from (user or project).
	Scope OptDeletePluginScope
	// Project root path for project-scoped plugins.
	ProjectRoot OptString
}

// DeletePluginBuildParams is parameters of DeletePluginBuild operation.
type DeletePluginBuildParams struct {
	// Artifact tag.
	Tag string
}

// DeleteRegistryParams is parameters of DeleteRegistry operation.
type DeleteRegistryParams struct {
	// Registry name.
	Name string
}

// DeleteSkillParams is parameters of DeleteSkill operation.
type DeleteSkillParams struct {
	// Skill name.
	Name string
	// Scope to uninstall from (user or project).
	Scope OptDeleteSkillScope
	// Project root path for project-scoped skills.
	ProjectRoot OptString
}

// DeleteSkillBuildParams is parameters of DeleteSkillBuild operation.
type DeleteSkillBuildParams struct {
	// Artifact tag.
	Tag string
}

// DeleteWorkloadParams is parameters of DeleteWorkload operation.
type DeleteWorkloadParams struct {
	// Workload name.
	Name string
}

// ExportWorkloadParams is parameters of ExportWorkload operation.
type ExportWorkloadParams struct {
	// Workload name.
	Name string
}

// GetGroupParams is parameters of GetGroup operation.
type GetGroupParams struct {
	// Group name.
	Name string
}

// GetLatestPublicRegistryServerParams is parameters of GetLatestPublicRegistryServer operation.
type GetLatestPublicRegistryServerParams struct {
	// Registry name (currently ignored, uses the default provider).
	RegistryName string
	// Server name (URL-encoded reverse-DNS format).
	ServerName string
}

// GetPluginParams is parameters of GetPlugin operation.
type GetPluginParams struct {
	// Plugin name.
	Name string
	// Filter by scope (user or project).
	Scope OptGetPluginScope
	// Project root path for project-scoped plugins.
	ProjectRoot OptString
}

// GetPluginContentParams is parameters of GetPluginContent operation.
type GetPluginContentParams struct {
	// OCI reference or local build tag.
	Ref string
}

// GetPublicRegistryPluginParams is parameters of GetPublicRegistryPlugin operation.
type GetPublicRegistryPluginParams struct {
	// Registry name (currently ignored, uses the default provider).
	RegistryName string
	// Plugin namespace in reverse-DNS format (e.g. io.github.stacklok).
	Namespace string
	// Plugin name.
	PluginName string
}

// GetPublicRegistrySkillParams is parameters of GetPublicRegistrySkill operation.
type GetPublicRegistrySkillParams struct {
	// Registry name (currently ignored, uses the default provider).
	RegistryName string
	// Skill namespace in reverse-DNS format (e.g. io.github.stacklok).
	Namespace string
	// Skill name.
	SkillName string
}

// GetRegistryParams is parameters of GetRegistry operation.
type GetRegistryParams struct {
	// Registry name.
	Name string
}

// GetRegistryServerParams is parameters of GetRegistryServer operation.
type GetRegistryServerParams struct {
	// Registry name.
	Name string
	// ImageMetadata name.
	ServerName string
}

// GetSkillParams is parameters of GetSkill operation.
type GetSkillParams struct {
	// Skill name.
	Name string
	// Filter by scope (user or project).
	Scope OptGetSkillScope
	// Project root path for project-scoped skills.
	ProjectRoot OptString
}

// GetSkillContentParams is parameters of GetSkillContent operation.
type GetSkillContentParams struct {
	// OCI reference or local build tag.
	Ref string
}

// GetWorkloadParams is parameters of GetWorkload operation.
type GetWorkloadParams struct {
	// Workload name.
	Name string
}

// GetWorkloadLogsParams is parameters of GetWorkloadLogs operation.
type GetWorkloadLogsParams struct {
	// Workload name.
	Name string
}

// GetWorkloadProxyLogsParams is parameters of GetWorkloadProxyLogs operation.
type GetWorkloadProxyLogsParams struct {
	// Workload name.
	Name string
}

// GetWorkloadStatusParams is parameters of GetWorkloadStatus operation.
type GetWorkloadStatusParams struct {
	// Workload name.
	Name string
}

// ListPluginsParams is parameters of ListPlugins operation.
type ListPluginsParams struct {
	// Filter by scope (user or project).
	Scope OptListPluginsScope
	// Filter by client app.
	Client OptString
	// Filter by project root path.
	ProjectRoot OptString
	// Filter by group name.
	Group OptString
}

// ListPublicRegistryPluginsParams is parameters of ListPublicRegistryPlugins operation.
type ListPublicRegistryPluginsParams struct {
	// Registry name (currently ignored, uses the default provider).
	RegistryName string
	// Search filter — matches against plugin name, namespace, and description.
	Q OptString
	// Page number, 1-based (default: 1).
	Page OptInt
	// Items per page, max 200 (default: 50).
	Limit OptInt
}

// ListPublicRegistryServersParams is parameters of ListPublicRegistryServers operation.
type ListPublicRegistryServersParams struct {
	// Registry name (currently ignored, uses the default provider).
	RegistryName string
	// Search filter — matches against server name and description.
	Q OptString
	// Page number, 1-based (default: 1).
	Page OptInt
	// Items per page, max 200 (default: 50).
	Limit OptInt
}

// ListPublicRegistrySkillsParams is parameters of ListPublicRegistrySkills operation.
type ListPublicRegistrySkillsParams struct {
	// Registry name (currently ignored, uses the default provider).
	RegistryName string
	// Search filter — matches against skill name, namespace, and description.
	Q OptString
	// Page number, 1-based (default: 1).
	Page OptInt
	// Items per page, max 200 (default: 50).
	Limit OptInt
}

// ListRegistryServersParams is parameters of ListRegistryServers operation.
type ListRegistryServersParams struct {
	// Registry name.
	Name string
}

// ListSkillsParams is parameters of ListSkills operation.
type ListSkillsParams struct {
	// Filter by scope (user or project).
	Scope OptListSkillsScope
	// Filter by client app.
	Client OptString
	// Filter by project root path.
	ProjectRoot OptString
	// Filter by group name.
	Group OptString
}

// ListWorkloadsParams is parameters of ListWorkloads operation.
type ListWorkloadsParams struct {
	// List all workloads, including stopped ones.
	All OptBool
	// Filter workloads by group name.
	Group OptString
}

// PushPluginParams is parameters of PushPlugin operation.
type PushPluginParams struct {
	// Local discovery capability (required with request.key).
	XToolhiveKeySigningCapability OptString
}

// PushSkillParams is parameters of PushSkill operation.
type PushSkillParams struct {
	// Local discovery capability (required with request.key).
	XToolhiveKeySigningCapability OptString
}

// RefreshRegistryParams is parameters of RefreshRegistry operation.
type RefreshRegistryParams struct {
	// Registry name (must be 'default').
	Name string
}

// RemoveClientFromGroupParams is parameters of RemoveClientFromGroup operation.
type RemoveClientFromGroupParams struct {
	// Client name to unregister.
	Name string
	// Group name to remove client from.
	Group string
}

// RestartWorkloadParams is parameters of RestartWorkload operation.
type RestartWorkloadParams struct {
	// Workload name.
	Name string
}

// StopWorkloadParams is parameters of StopWorkload operation.
type StopWorkloadParams struct {
	// Workload name.
	Name string
}

// UnregisterClientParams is parameters of UnregisterClient operation.
type UnregisterClientParams struct {
	// Client name to unregister.
	Name string
}

// UpdateDefaultSecretParams is parameters of UpdateDefaultSecret operation.
type UpdateDefaultSecretParams struct {
	// Secret key.
	Key string
}

// UpdateRegistryParams is parameters of UpdateRegistry operation.
type UpdateRegistryParams struct {
	// Registry name (must be 'default').
	Name string
}

// UpdateWorkloadParams is parameters of UpdateWorkload operation.
type UpdateWorkloadParams struct {
	// Workload name.
	Name string
}

// UpgradeWorkloadParams is parameters of UpgradeWorkload operation.
type UpgradeWorkloadParams struct {
	// Workload name.
	Name string
}
