// Code generated by MockGen. DO NOT EDIT.
// Source: 1password.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_onepassword.go -package=mocks -source=1password.go OPSecretsService
//

// Package mocks is a generated GoMock package.
package mocks
