// SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0

// TODO: Follow-up issue tracks infra-heavy tests that need JWT/OIDC, circuit
// breaker, Redis session, and Tier-2 TEI embedding infrastructure:
// https://github.com/stacklok/toolhive/issues/4944

package e2e_test

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"gopkg.in/yaml.v3"

	thvjson "github.com/stacklok/toolhive/pkg/json"
	"github.com/stacklok/toolhive/pkg/vmcp"
	vmcpconfig "github.com/stacklok/toolhive/pkg/vmcp/config"
	"github.com/stacklok/toolhive/test/e2e"
	"github.com/stacklok/toolhive/test/e2e/images"
)

// modifyVMCPConfig reads a vMCP YAML config file, calls fn to mutate it, then
// writes it back. Used to layer feature-specific settings on top of a base
// config generated by `thv vmcp init`.
func modifyVMCPConfig(path string, fn func(*vmcpconfig.Config)) error {
	data, err := os.ReadFile(path) //nolint:gosec // path is test-controlled
	if err != nil {
		return fmt.Errorf("reading vmcp config %s: %w", path, err)
	}
	var cfg vmcpconfig.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return fmt.Errorf("unmarshalling vmcp config: %w", err)
	}
	fn(&cfg)
	out, err := yaml.Marshal(&cfg)
	if err != nil {
		return fmt.Errorf("marshalling vmcp config: %w", err)
	}
	if err := os.WriteFile(path, out, 0o600); err != nil {
		return fmt.Errorf("writing vmcp config %s: %w", path, err)
	}
	return nil
}

// startYardstick runs a yardstick backend in the given group and waits for it
// to be ready. Yardstick exposes an "echo" tool over streamable-http on port 8080.
func startYardstick(config *e2e.TestConfig, groupName, backendName string) {
	e2e.NewTHVCommand(config,
		"run", images.YardstickServerImage,
		"--name", backendName,
		"--group", groupName,
		"--transport", "streamable-http",
		"--target-port", "8080",
		"--env", "TRANSPORT=streamable-http",
	).ExpectSuccess()
	err := e2e.WaitForMCPServer(config, backendName, 120*time.Second)
	Expect(err).ToNot(HaveOccurred(), fmt.Sprintf("yardstick backend %q should become running", backendName))
}

// initVMCPConfig generates a starter YAML config for the given group into path
// using `thv vmcp init`.
func initVMCPConfig(config *e2e.TestConfig, groupName, path string) {
	e2e.NewTHVCommand(config,
		"vmcp", "init",
		"--group", groupName,
		"--config", path,
	).ExpectSuccess()
}

var _ = Describe("vMCP CLI features", Label("vmcp", "e2e", "features"), func() {

	// -------------------------------------------------------------------------
	// Context 1: Conflict resolution — prefix strategy
	// Two identical yardstick backends expose the same tool names. With prefix
	// strategy enabled, both sets of tools appear with backend-name prefixes.
	// -------------------------------------------------------------------------
	Context("conflict resolution (prefix strategy)", func() {
		var (
			cfg          *e2e.TestConfig
			groupName    string
			backendAName string
			backendBName string
			vMCPCmd      *exec.Cmd
			vMCPPort     int
			tmpDir       string
		)

		BeforeEach(func() {
			cfg = e2e.NewTestConfig()
			groupName = e2e.GenerateUniqueServerName("vmcp-feat-conflict")
			backendAName = e2e.GenerateUniqueServerName("yardstick-a")
			backendBName = e2e.GenerateUniqueServerName("yardstick-b")
			vMCPPort = allocateVMCPPort()
			var err error
			tmpDir, err = os.MkdirTemp("", "vmcp-feat-conflict-*")
			Expect(err).ToNot(HaveOccurred())
			DeferCleanup(func() { _ = os.RemoveAll(tmpDir) })

			Expect(e2e.CheckTHVBinaryAvailable(cfg)).To(Succeed())

			By("creating group and two yardstick backends")
			e2e.NewTHVCommand(cfg, "group", "create", groupName).ExpectSuccess()
			startYardstick(cfg, groupName, backendAName)
			startYardstick(cfg, groupName, backendBName)
		})

		AfterEach(func() {
			stopVMCPProcess(vMCPCmd)
			if cfg.CleanupAfter {
				if err := e2e.StopAndRemoveMCPServer(cfg, backendAName); err != nil {
					GinkgoWriter.Printf("cleanup: StopAndRemoveMCPServer(%s) failed: %v\n", backendAName, err)
				}
				if err := e2e.StopAndRemoveMCPServer(cfg, backendBName); err != nil {
					GinkgoWriter.Printf("cleanup: StopAndRemoveMCPServer(%s) failed: %v\n", backendBName, err)
				}
				if err := e2e.RemoveGroup(cfg, groupName); err != nil {
					GinkgoWriter.Printf("cleanup: RemoveGroup(%s) failed: %v\n", groupName, err)
				}
			}
		})

		It("prefixes tool names with backend names so both echo tools are visible", func() {
			configPath := filepath.Join(tmpDir, "vmcp.yaml")
			initVMCPConfig(cfg, groupName, configPath)

			Expect(modifyVMCPConfig(configPath, func(c *vmcpconfig.Config) {
				if c.Aggregation == nil {
					c.Aggregation = &vmcpconfig.AggregationConfig{}
				}
				c.Aggregation.ConflictResolution = vmcp.ConflictStrategyPrefix
				c.Aggregation.ConflictResolutionConfig = &vmcpconfig.ConflictResolutionConfig{
					PrefixFormat: "{workload}_",
				}
			})).To(Succeed())

			By("starting vMCP serve with prefix config")
			vMCPCmd = e2e.StartLongRunningTHVCommand(cfg,
				"vmcp", "serve",
				"--config", configPath,
				"--port", fmt.Sprintf("%d", vMCPPort),
			)
			DeferCleanup(func() { stopVMCPProcess(vMCPCmd) })

			vMCPURL := fmt.Sprintf("http://127.0.0.1:%d/mcp", vMCPPort)
			Expect(e2e.WaitForMCPServerReady(cfg, vMCPURL, "streamable-http", 60*time.Second)).To(Succeed())

			By("listing tools and verifying prefix strategy")
			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			mcpClient, err := e2e.NewMCPClientForStreamableHTTP(cfg, vMCPURL)
			Expect(err).ToNot(HaveOccurred())
			defer func() { _ = mcpClient.Close() }()
			Expect(mcpClient.Initialize(ctx)).To(Succeed())

			tools, err := mcpClient.ListTools(ctx)
			Expect(err).ToNot(HaveOccurred())

			var echoTools []string
			for _, t := range tools.Tools {
				if strings.Contains(t.Name, "echo") {
					echoTools = append(echoTools, t.Name)
				}
			}
			By(fmt.Sprintf("found echo tools: %v", echoTools))
			Expect(echoTools).To(HaveLen(2), "prefix strategy should expose one echo tool per backend")

			hasA := false
			hasB := false
			for _, name := range echoTools {
				if strings.HasPrefix(name, backendAName+"_") {
					hasA = true
				}
				if strings.HasPrefix(name, backendBName+"_") {
					hasB = true
				}
			}
			Expect(hasA).To(BeTrue(), fmt.Sprintf("expected echo tool prefixed with %s_", backendAName))
			Expect(hasB).To(BeTrue(), fmt.Sprintf("expected echo tool prefixed with %s_", backendBName))
		})
	})

	// -------------------------------------------------------------------------
	// Context 2: Tool filtering — per-workload allow-list + ExcludeAll
	// backendA exposes only "echo"; backendB is completely hidden.
	// -------------------------------------------------------------------------
	Context("tool filtering (per-workload filter + ExcludeAll)", func() {
		var (
			cfg          *e2e.TestConfig
			groupName    string
			backendAName string
			backendBName string
			vMCPCmd      *exec.Cmd
			vMCPPort     int
			tmpDir       string
		)

		BeforeEach(func() {
			cfg = e2e.NewTestConfig()
			groupName = e2e.GenerateUniqueServerName("vmcp-feat-filter")
			backendAName = e2e.GenerateUniqueServerName("yardstick-a")
			backendBName = e2e.GenerateUniqueServerName("yardstick-b")
			vMCPPort = allocateVMCPPort()
			var err error
			tmpDir, err = os.MkdirTemp("", "vmcp-feat-filter-*")
			Expect(err).ToNot(HaveOccurred())
			DeferCleanup(func() { _ = os.RemoveAll(tmpDir) })

			Expect(e2e.CheckTHVBinaryAvailable(cfg)).To(Succeed())

			By("creating group and two yardstick backends")
			e2e.NewTHVCommand(cfg, "group", "create", groupName).ExpectSuccess()
			startYardstick(cfg, groupName, backendAName)
			startYardstick(cfg, groupName, backendBName)
		})

		AfterEach(func() {
			stopVMCPProcess(vMCPCmd)
			if cfg.CleanupAfter {
				if err := e2e.StopAndRemoveMCPServer(cfg, backendAName); err != nil {
					GinkgoWriter.Printf("cleanup: StopAndRemoveMCPServer(%s) failed: %v\n", backendAName, err)
				}
				if err := e2e.StopAndRemoveMCPServer(cfg, backendBName); err != nil {
					GinkgoWriter.Printf("cleanup: StopAndRemoveMCPServer(%s) failed: %v\n", backendBName, err)
				}
				if err := e2e.RemoveGroup(cfg, groupName); err != nil {
					GinkgoWriter.Printf("cleanup: RemoveGroup(%s) failed: %v\n", groupName, err)
				}
			}
		})

		It("only exposes the filtered tool from backendA; backendB tools are hidden", func() {
			configPath := filepath.Join(tmpDir, "vmcp.yaml")
			initVMCPConfig(cfg, groupName, configPath)

			Expect(modifyVMCPConfig(configPath, func(c *vmcpconfig.Config) {
				if c.Aggregation == nil {
					c.Aggregation = &vmcpconfig.AggregationConfig{}
				}
				c.Aggregation.ConflictResolution = vmcp.ConflictStrategyPrefix
				c.Aggregation.ConflictResolutionConfig = &vmcpconfig.ConflictResolutionConfig{
					PrefixFormat: "{workload}_",
				}
				c.Aggregation.Tools = []*vmcpconfig.WorkloadToolConfig{
					{Workload: backendAName, Filter: []string{"echo"}},
					{Workload: backendBName, ExcludeAll: true},
				}
			})).To(Succeed())

			By("starting vMCP serve with filter config")
			vMCPCmd = e2e.StartLongRunningTHVCommand(cfg,
				"vmcp", "serve",
				"--config", configPath,
				"--port", fmt.Sprintf("%d", vMCPPort),
			)
			DeferCleanup(func() { stopVMCPProcess(vMCPCmd) })

			vMCPURL := fmt.Sprintf("http://127.0.0.1:%d/mcp", vMCPPort)
			Expect(e2e.WaitForMCPServerReady(cfg, vMCPURL, "streamable-http", 60*time.Second)).To(Succeed())

			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			mcpClient, err := e2e.NewMCPClientForStreamableHTTP(cfg, vMCPURL)
			Expect(err).ToNot(HaveOccurred())
			defer func() { _ = mcpClient.Close() }()
			Expect(mcpClient.Initialize(ctx)).To(Succeed())

			tools, err := mcpClient.ListTools(ctx)
			Expect(err).ToNot(HaveOccurred())

			By(fmt.Sprintf("verifying tool visibility; got %d tools", len(tools.Tools)))
			var echoCount int
			for _, t := range tools.Tools {
				Expect(t.Name).ToNot(ContainSubstring(backendBName),
					"backendB tools must be hidden via ExcludeAll")
				if strings.Contains(t.Name, "echo") {
					echoCount++
				}
			}
			Expect(echoCount).To(Equal(1), "only backendA echo should be visible")
		})
	})

	// -------------------------------------------------------------------------
	// Context 3: Global ExcludeAll — all backend tools hidden
	// tools/list must succeed but return an empty slice.
	// -------------------------------------------------------------------------
	Context("global ExcludeAll (all tools hidden)", func() {
		var (
			cfg         *e2e.TestConfig
			groupName   string
			backendName string
			vMCPCmd     *exec.Cmd
			vMCPPort    int
			tmpDir      string
		)

		BeforeEach(func() {
			cfg = e2e.NewTestConfig()
			groupName = e2e.GenerateUniqueServerName("vmcp-feat-excludeall")
			backendName = e2e.GenerateUniqueServerName("yardstick")
			vMCPPort = allocateVMCPPort()
			var err error
			tmpDir, err = os.MkdirTemp("", "vmcp-feat-excludeall-*")
			Expect(err).ToNot(HaveOccurred())
			DeferCleanup(func() { _ = os.RemoveAll(tmpDir) })

			Expect(e2e.CheckTHVBinaryAvailable(cfg)).To(Succeed())

			By("creating group and one yardstick backend")
			e2e.NewTHVCommand(cfg, "group", "create", groupName).ExpectSuccess()
			startYardstick(cfg, groupName, backendName)
		})

		AfterEach(func() {
			stopVMCPProcess(vMCPCmd)
			if cfg.CleanupAfter {
				if err := e2e.StopAndRemoveMCPServer(cfg, backendName); err != nil {
					GinkgoWriter.Printf("cleanup: StopAndRemoveMCPServer(%s) failed: %v\n", backendName, err)
				}
				if err := e2e.RemoveGroup(cfg, groupName); err != nil {
					GinkgoWriter.Printf("cleanup: RemoveGroup(%s) failed: %v\n", groupName, err)
				}
			}
		})

		It("returns an empty tools list when ExcludeAllTools is true", func() {
			configPath := filepath.Join(tmpDir, "vmcp.yaml")
			initVMCPConfig(cfg, groupName, configPath)

			Expect(modifyVMCPConfig(configPath, func(c *vmcpconfig.Config) {
				if c.Aggregation == nil {
					c.Aggregation = &vmcpconfig.AggregationConfig{}
				}
				c.Aggregation.ConflictResolution = vmcp.ConflictStrategyPrefix
				c.Aggregation.ExcludeAllTools = true
			})).To(Succeed())

			By("starting vMCP serve with ExcludeAllTools")
			vMCPCmd = e2e.StartLongRunningTHVCommand(cfg,
				"vmcp", "serve",
				"--config", configPath,
				"--port", fmt.Sprintf("%d", vMCPPort),
			)
			DeferCleanup(func() { stopVMCPProcess(vMCPCmd) })

			vMCPURL := fmt.Sprintf("http://127.0.0.1:%d/mcp", vMCPPort)
			Expect(e2e.WaitForMCPServerReady(cfg, vMCPURL, "streamable-http", 60*time.Second)).To(Succeed())

			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			mcpClient, err := e2e.NewMCPClientForStreamableHTTP(cfg, vMCPURL)
			Expect(err).ToNot(HaveOccurred())
			defer func() { _ = mcpClient.Close() }()
			Expect(mcpClient.Initialize(ctx)).To(Succeed())

			tools, err := mcpClient.ListTools(ctx)
			Expect(err).ToNot(HaveOccurred(), "tools/list must succeed even when all tools are hidden")
			Expect(tools.Tools).To(BeEmpty(), "ExcludeAllTools should hide all backend tools")
		})
	})

	// -------------------------------------------------------------------------
	// Context 4: Composite sequential tool
	// An "echo_twice" composite calls yardstick's echo tool twice in sequence.
	// Verifies that: (a) the composite appears in tools/list, (b) calling it
	// with a message argument succeeds and returns non-empty content.
	// -------------------------------------------------------------------------
	Context("composite sequential tool", func() {
		var (
			cfg         *e2e.TestConfig
			groupName   string
			backendName string
			vMCPCmd     *exec.Cmd
			vMCPPort    int
			tmpDir      string
		)

		BeforeEach(func() {
			cfg = e2e.NewTestConfig()
			groupName = e2e.GenerateUniqueServerName("vmcp-feat-composite")
			backendName = e2e.GenerateUniqueServerName("yardstick")
			vMCPPort = allocateVMCPPort()
			var err error
			tmpDir, err = os.MkdirTemp("", "vmcp-feat-composite-*")
			Expect(err).ToNot(HaveOccurred())
			DeferCleanup(func() { _ = os.RemoveAll(tmpDir) })

			Expect(e2e.CheckTHVBinaryAvailable(cfg)).To(Succeed())

			By("creating group and one yardstick backend")
			e2e.NewTHVCommand(cfg, "group", "create", groupName).ExpectSuccess()
			startYardstick(cfg, groupName, backendName)
		})

		AfterEach(func() {
			stopVMCPProcess(vMCPCmd)
			if cfg.CleanupAfter {
				if err := e2e.StopAndRemoveMCPServer(cfg, backendName); err != nil {
					GinkgoWriter.Printf("cleanup: StopAndRemoveMCPServer(%s) failed: %v\n", backendName, err)
				}
				if err := e2e.RemoveGroup(cfg, groupName); err != nil {
					GinkgoWriter.Printf("cleanup: RemoveGroup(%s) failed: %v\n", groupName, err)
				}
			}
		})

		It("exposes the composite tool in tools/list and executes it successfully", func() {
			configPath := filepath.Join(tmpDir, "vmcp.yaml")
			initVMCPConfig(cfg, groupName, configPath)

			Expect(modifyVMCPConfig(configPath, func(c *vmcpconfig.Config) {
				if c.Aggregation == nil {
					c.Aggregation = &vmcpconfig.AggregationConfig{}
				}
				// ConflictResolution is required by the aggregation validator.
				c.Aggregation.ConflictResolution = vmcp.ConflictStrategyPrefix

				c.CompositeTools = []vmcpconfig.CompositeToolConfig{
					{
						Name:        "echo_twice",
						Description: "Echoes the input message twice in sequence",
						Parameters: thvjson.NewMap(map[string]any{
							"type": "object",
							"properties": map[string]any{
								"message": map[string]any{
									"type":        "string",
									"description": "The message to echo twice",
								},
							},
							"required": []any{"message"},
						}),
						Steps: []vmcpconfig.WorkflowStepConfig{
							{
								ID:   "first_echo",
								Type: "tool",
								Tool: fmt.Sprintf("%s.echo", backendName),
								Arguments: thvjson.NewMap(map[string]any{
									"input": "{{ .params.message }}",
								}),
							},
							{
								ID:        "second_echo",
								Type:      "tool",
								Tool:      fmt.Sprintf("%s.echo", backendName),
								DependsOn: []string{"first_echo"},
								Arguments: thvjson.NewMap(map[string]any{
									"input": "{{ .steps.first_echo.content.text }}",
								}),
							},
						},
					},
				}
			})).To(Succeed())

			By("starting vMCP serve with composite tool config")
			vMCPCmd = e2e.StartLongRunningTHVCommand(cfg,
				"vmcp", "serve",
				"--config", configPath,
				"--port", fmt.Sprintf("%d", vMCPPort),
			)
			DeferCleanup(func() { stopVMCPProcess(vMCPCmd) })

			vMCPURL := fmt.Sprintf("http://127.0.0.1:%d/mcp", vMCPPort)
			Expect(e2e.WaitForMCPServerReady(cfg, vMCPURL, "streamable-http", 60*time.Second)).To(Succeed())

			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			mcpClient, err := e2e.NewMCPClientForStreamableHTTP(cfg, vMCPURL)
			Expect(err).ToNot(HaveOccurred())
			defer func() { _ = mcpClient.Close() }()
			Expect(mcpClient.Initialize(ctx)).To(Succeed())

			By("verifying echo_twice appears in tools/list")
			tools, err := mcpClient.ListTools(ctx)
			Expect(err).ToNot(HaveOccurred())

			var foundComposite bool
			for _, t := range tools.Tools {
				if t.Name == "echo_twice" {
					foundComposite = true
					Expect(t.Description).To(Equal("Echoes the input message twice in sequence"))
					break
				}
			}
			Expect(foundComposite).To(BeTrue(), "echo_twice composite tool must appear in tools/list")

			By("calling echo_twice and verifying non-empty result")
			result, err := mcpClient.CallTool(ctx, "echo_twice", map[string]any{
				"message": "hello composite",
			})
			Expect(err).ToNot(HaveOccurred(), "composite tool call must succeed")
			Expect(result.Content).ToNot(BeEmpty(), "composite tool must return content")
		})
	})

	// -------------------------------------------------------------------------
	// Context 5: Tier-1 optimizer (FTS5) — quick mode
	// `thv vmcp serve --group <name> --optimizer` must expose exactly two tools:
	// find_tool and call_tool. Calling find_tool with a query must return results.
	// -------------------------------------------------------------------------
	Context("Tier-1 optimizer (--optimizer flag, quick mode)", func() {
		var (
			cfg         *e2e.TestConfig
			groupName   string
			backendName string
			vMCPCmd     *exec.Cmd
			vMCPPort    int
		)

		BeforeEach(func() {
			cfg = e2e.NewTestConfig()
			groupName = e2e.GenerateUniqueServerName("vmcp-feat-optimizer")
			backendName = e2e.GenerateUniqueServerName("yardstick")
			vMCPPort = allocateVMCPPort()

			Expect(e2e.CheckTHVBinaryAvailable(cfg)).To(Succeed())

			By("creating group and one yardstick backend")
			e2e.NewTHVCommand(cfg, "group", "create", groupName).ExpectSuccess()
			startYardstick(cfg, groupName, backendName)
		})

		AfterEach(func() {
			stopVMCPProcess(vMCPCmd)
			if cfg.CleanupAfter {
				if err := e2e.StopAndRemoveMCPServer(cfg, backendName); err != nil {
					GinkgoWriter.Printf("cleanup: StopAndRemoveMCPServer(%s) failed: %v\n", backendName, err)
				}
				if err := e2e.RemoveGroup(cfg, groupName); err != nil {
					GinkgoWriter.Printf("cleanup: RemoveGroup(%s) failed: %v\n", groupName, err)
				}
			}
		})

		It("exposes only find_tool and call_tool when --optimizer is set", func() {
			By("starting vMCP serve in quick mode with --optimizer")
			vMCPCmd = e2e.StartLongRunningTHVCommand(cfg,
				"vmcp", "serve",
				"--group", groupName,
				"--optimizer",
				"--port", fmt.Sprintf("%d", vMCPPort),
			)
			DeferCleanup(func() { stopVMCPProcess(vMCPCmd) })

			vMCPURL := fmt.Sprintf("http://127.0.0.1:%d/mcp", vMCPPort)
			Expect(e2e.WaitForMCPServerReady(cfg, vMCPURL, "streamable-http", 60*time.Second)).To(Succeed())

			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			mcpClient, err := e2e.NewMCPClientForStreamableHTTP(cfg, vMCPURL)
			Expect(err).ToNot(HaveOccurred())
			defer func() { _ = mcpClient.Close() }()
			Expect(mcpClient.Initialize(ctx)).To(Succeed())

			By("verifying only find_tool and call_tool are exposed")
			tools, err := mcpClient.ListTools(ctx)
			Expect(err).ToNot(HaveOccurred())
			Expect(tools.Tools).To(HaveLen(2), "optimizer mode must expose exactly 2 tools")

			names := make([]string, len(tools.Tools))
			for i, t := range tools.Tools {
				names[i] = t.Name
			}
			Expect(names).To(ConsistOf("find_tool", "call_tool"))

			By("calling find_tool to verify it returns results")
			result, err := mcpClient.CallTool(ctx, "find_tool", map[string]any{
				"tool_description": "echo a message",
			})
			Expect(err).ToNot(HaveOccurred(), "find_tool must succeed")
			Expect(result.Content).ToNot(BeEmpty(), "find_tool must return tool suggestions")
		})
	})

}) // end Describe("vMCP CLI features")
