apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mkp
  namespace: toolhive-system
spec:
  image: ghcr.io/stackloklabs/mkp/server
  transport: sse
  port: 8080
  permissionProfile:
    type: builtin
    name: network
  podTemplateSpec:
    spec:
      # this will not be needed once we have implemented separate 
      # service accounts for each MCP server and its proxyrunner
      serviceAccountName: mkp-proxy-runner
      containers:
      - name: mcp
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
