apiVersion: v1
kind: Secret
metadata:
  name: oidc-client-secret
  namespace: toolhive-system
type: Opaque
stringData:
  client-secret: "your-oidc-client-secret-value"
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: secure-fetch-inline-secretref
  namespace: toolhive-system
spec:
  image: docker.io/mcp/fetch
  transport: stdio
  port: 8080
  oidcConfig:
    type: inline
    inline:
      issuer: "https://my-oidc-provider.com"
      audience: "my-audience"
      jwksUrl: "https://my-oidc-provider.com/.well-known/jwks.json"
      introspectionUrl: "https://my-oidc-provider.com/oauth/introspect"
      clientId: "my-client-id"
      # Use clientSecretRef to reference a Kubernetes Secret instead of hardcoding the secret
      clientSecretRef:
        name: oidc-client-secret
        key: client-secret
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
