apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mkp
  namespace: toolhive-system
spec:
  image: ghcr.io/stackloklabs/mkp/server
  transport: streamable-http
  targetPort: 8080
  port: 8080
  args:
    # Change to true for read-write access.
    - --read-write=false
  # We create this service account below with the desired permissions.
  serviceAccount: mkp-sa
  resources:
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '50m'
      memory: '64Mi'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mkp-sa
  namespace: toolhive-system
---
# NOTE: This ClusterRoleBinding uses cluster-admin for example purposes only.
# In production, you should create a custom ClusterRole with the minimum
# permissions required by your MCP server instead of using cluster-admin.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mkp-sa-cluster-admin
subjects:
  - kind: ServiceAccount
    name: mkp-sa
    namespace: toolhive-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
