apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: github-with-overrides
  namespace: toolhive-system
spec:
  image: docker.io/mcp/github
  transport: stdio
  proxyPort: 8080
  secrets:
    - name: github-token
      key: GITHUB_PERSONAL_ACCESS_TOKEN
  env:
    - name: GITHUB_API_URL
      value: https://api.github.com
    - name: LOG_LEVEL
      value: info
  # Resource requirements for the MCP server container (the actual workload)
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

  # Resource requirements for the ToolHive proxy runner container (infrastructure)
  # The proxy runner is lighter weight and typically needs fewer resources
  # Defaults: 50m/200m CPU, 64Mi/256Mi memory
  proxyRunnerResources:
    limits:
      cpu: "150m"      # Override default limit of 200m
      memory: "192Mi"  # Override default limit of 256Mi
    requests:
      cpu: "75m"       # Override default request of 50m
      memory: "96Mi"   # Override default request of 64Mi

  resourceOverrides:
    proxyDeployment:
      # Annotations and labels for the proxy deployment
      annotations:
        example.com/deployment-annotation: "custom-deployment-value"
        monitoring.example.com/scrape: "true"
        monitoring.example.com/port: "8080"
      labels:
        example.com/deployment-label: "custom-deployment-label"
        environment: "production"
        team: "platform"

      # Environment variables for the proxy runner container (thv-proxyrunner)
      # These affect the ToolHive proxy itself, not the MCP server it manages
      env:
        - name: CUSTOM_PROXY_VAR
          value: "custom-value"
        - name: TOOLHIVE_DEBUG
          value: "true"  # Enable debug logging to see detailed token exchange, middleware, and proxy logs
    proxyService:
      annotations:
        example.com/service-annotation: "custom-service-value"
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        external-dns.alpha.kubernetes.io/hostname: "github-mcp.example.com"
      labels:
        example.com/service-label: "custom-service-label"
        environment: "production"
        team: "platform"