apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: sample-with-pod-template
spec:
  image: ghcr.io/stackloklabs/mcp-fetch:latest
  transport: sse
  proxyPort: 8080
  # Example of using the PodTemplateSpec to customize the pod
  podTemplateSpec:
    spec:
      # Add tolerations to run on nodes with specific taints
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "mcp-servers"
        effect: "NoSchedule"
      # Add node selector to run on specific nodes
      nodeSelector:
        kubernetes.io/os: linux
        node-type: mcp-server
      # Add security context for the pod
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      # Customize the MCP container
      containers:
      - name: mcp
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsUser: 1000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"