apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: secure-fetch-inline
  namespace: toolhive-system
spec:
  image: docker.io/mcp/fetch
  transport: stdio
  port: 8080
  permissionProfile:
    type: builtin
    name: network
  oidcConfig:
    type: inline
    inline:
      issuer: "https://my-oidc-provider.com"
      audience: "my-audience"
      jwksUrl: "https://my-oidc-provider.com/.well-known/jwks.json"
      clientId: "my-client-id"
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
