# Example: MCPServer with inline OIDC configuration
# Note: For production use with client secrets, see mcpserver_with_inline_oidc_secretref.yaml
# which demonstrates the recommended clientSecretRef approach instead of plaintext clientSecret.
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: secure-fetch-inline
  namespace: toolhive-system
spec:
  image: docker.io/mcp/fetch
  transport: stdio
  proxyPort: 8080
  oidcConfig:
    type: inline
    inline:
      issuer: "https://my-oidc-provider.com"
      audience: "my-audience"
      jwksUrl: "https://my-oidc-provider.com/.well-known/jwks.json"
      clientId: "my-client-id"
      # Optional: For production, use clientSecretRef instead of clientSecret
      # clientSecretRef:
      #   name: oidc-client-secret
      #   key: client-secret
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
