// Code generated by MockGen. DO NOT EDIT.
// Source: registry_service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_registry_service.go -package=mocks -source=registry_service.go RegistryConfigService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistryConfigService is a mock of RegistryConfigService interface.
type MockRegistryConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryConfigServiceMockRecorder
	isgomock struct{}
}

// MockRegistryConfigServiceMockRecorder is the mock recorder for MockRegistryConfigService.
type MockRegistryConfigServiceMockRecorder struct {
	mock *MockRegistryConfigService
}

// NewMockRegistryConfigService creates a new mock instance.
func NewMockRegistryConfigService(ctrl *gomock.Controller) *MockRegistryConfigService {
	mock := &MockRegistryConfigService{ctrl: ctrl}
	mock.recorder = &MockRegistryConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryConfigService) EXPECT() *MockRegistryConfigServiceMockRecorder {
	return m.recorder
}

// GetRegistryInfo mocks base method.
func (m *MockRegistryConfigService) GetRegistryInfo() (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistryInfo")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// GetRegistryInfo indicates an expected call of GetRegistryInfo.
func (mr *MockRegistryConfigServiceMockRecorder) GetRegistryInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistryInfo", reflect.TypeOf((*MockRegistryConfigService)(nil).GetRegistryInfo))
}

// SetRegistryFromInput mocks base method.
func (m *MockRegistryConfigService) SetRegistryFromInput(input string, allowPrivateIP bool) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRegistryFromInput", input, allowPrivateIP)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetRegistryFromInput indicates an expected call of SetRegistryFromInput.
func (mr *MockRegistryConfigServiceMockRecorder) SetRegistryFromInput(input, allowPrivateIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegistryFromInput", reflect.TypeOf((*MockRegistryConfigService)(nil).SetRegistryFromInput), input, allowPrivateIP)
}

// UnsetRegistry mocks base method.
func (m *MockRegistryConfigService) UnsetRegistry() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetRegistry")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsetRegistry indicates an expected call of UnsetRegistry.
func (mr *MockRegistryConfigServiceMockRecorder) UnsetRegistry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetRegistry", reflect.TypeOf((*MockRegistryConfigService)(nil).UnsetRegistry))
}
